Transform: AWS::Serverless-2016-10-31

Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.

Resources:
  WorkerLambdaRole:
    Metadata:
      "aws:copilot:description": "An IAM role for the worker lambda"
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole

  WorkerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/worker
      Handler: index.handler
      Runtime: nodejs16.x
      Timeout: 30
      MemorySize: 512
      Role: !GetAtt "WorkerLambdaRole.Arn"
      Events:
        Requests:
          Type: SNS
          Properties:
            Topic: !Sub arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${App}-${Env}-${Name}-requests
            SqsSubscription: true
